# Generated by Django 4.2.4 on 2023-09-05 10:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(default=None, max_length=250, null=True, upload_to='product_images/')),
                ('product_title', models.CharField(max_length=100)),
                ('product_des', tinymce.models.HTMLField()),
                ('product_price', models.CharField(max_length=50)),
            ],
        ),
    ]
