# Generated by Django 4.2.4 on 2023-10-07 06:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('StyleVaneApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.FileField(default=None, max_length=250, null=True, upload_to='blog_images/')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_des', tinymce.models.HTMLField()),
            ],
        ),
    ]
